### ISSUE TITLE
This version still has a leak.

### ISSUE THREAD

**Issue by danfuzz** [digitalloggers/race-as-promised#1]
Just wanted to let you know that the version of the code you have still has a bit of a leak. For more info, please see <https://github.com/danfuzz/lactoserv/pull/173>.

**Comment by szakharchenko** [comment]
Thanks for the heads-up, sorry for not addressing this earlier. I have no test case for this; it would be nice if you confirmed #2 makes sense.

**Comment by danfuzz** [comment]
>I have no test case for this

This issue is a near-perfect poster child for the debate about whether or not it's worth it to have full test coverage.

Will look in a sec…
